### ISSUE TITLE
size of dataset dimension

### ISSUE THREAD

**Issue by NisanurBulut** [Vonatzki/pham_dimov_python#1]
Hello Vonatzki,
What should be the size of the test data set ? I have a dataset of one-dimensional integers.. I wantt o use pham's method. but Nd>1 so, Cant I use it ?

**Comment by Vonatzki** [comment]
You are correct. You can't use this function if N_d <= 1. It is not advised to apply clustering methods meant for multidimensional datasets to one-dimensional ones. This [StackOverflow](https://stackoverflow.com/questions/11513484/1d-number-array-clustering) link says that you may use kernel density estimation instead.
